### ISSUE TITLE
Difference between ur3_dual.py and ur3_dual_x.py

### ISSUE THREAD

**Issue by Shogo-Hayakawa** [wanweiwei07/wrs#1]
robobsim/robots/ur3_dual内のur3_dual.pyと、robotcon/ur/ur3_dual_x.pyについてです。
ur3_dual.py内の関数fkでは、398行目と399行目で

'lft_arm' -> jnt_values[0:6]
'rgt_arm' -> jnt_values[6:12]

のように左右の関節角度を取り出していますが、
ur3_dual_x.py内の関数move_jntsでは、65行目と66行目で

self._rgt_arm_hnd.move_jnts -> jnt_values[0:6]
self._rgt_arm_hnd.move_jnts -> jnt_values[6:12]

のように先程と左右が逆の取り出し方をしており、シミュレーションと実機を同時に使いたい場合に少し不便に感じます。
どちらかに統一していただけると嬉しいです。

**Comment by wanweiwei07** [comment]
ご指摘ありがとうございます．左優先として統一しました．
