### ISSUE TITLE
potential bug in `robot_sim/_kinematics/collision_checker.add_cdobj`

### ISSUE THREAD

**Issue by chenhaox** [wanweiwei07/wrs#10]
The function `add_cdobj`  in `robot_sim/_kinematics/collision_checker.py` directly use the reference of the `objcm`. During `fk`, the position of the `objcm` will be updated. I am not sure this is a feature or a potential bug.

**Comment by wanweiwei07** [comment]
The fk function updates objcm after it is added to the self.oih_info list by the self.hold function, which means the object is held by the robot and thus should be updated accordingly.
