### ISSUE TITLE
robot_sim.robots.ur3_dual.ur3_dual.py のバグ

### ISSUE THREAD

**Issue by tkmrym** [wanweiwei07/wrs#13]
`robot_sim.robots.ur3_dual.ur3_dual.py` 内の `gen_meshmodel` 関数の定義で呼び出されている `self.lft_hnd.gen_meshmodel`と`self.rgt_hnd.gen_meshmodel` の引数が間違っているようです．原因は`robot_sim.end_effectors.grippers.robotiq85.robotiq85.py`の`gen_meshmodel`の引数が変更されたことのようで，以下のように引数`tcp_loc_pos`と`tcp_loc_rotmat`を削除するとうまく動きました．
```
self.lft_hnd.gen_meshmodel(toggle_tcpcs=False,
                           toggle_jntscs=toggle_jntscs,
                           rgba=rgba).attach_to(meshmodel)
self.rgt_hnd.gen_meshmodel(toggle_tcpcs=False,
                           toggle_jntscs=toggle_jntscs,
                           rgba=rgba).attach_to(meshmodel)
```

**Comment by wanweiwei07** [comment]
どうもありがとうございました！更新済でした．
