### ISSUE TITLE
Difference between ur3_dual.py and ur3_dual_x.py

### ISSUE THREAD

**Issue by Shogo-Hayakawa** [wanweiwei07/wrs#2]
robobsim/robots/ur3_dual内のur3_dual.pyと、robotcon/ur/ur3_dual_x.pyについてです。

ur3_dual.py内の関数fkにjoint_valuesを渡す時は、joint_valuesの各値はradianに変換されたものを代入する必要がありますが、
ur3_dual_x.py内の関数move_jntsについては、150行目でjoint_valuesの各値がradianに変換されるので、move_jntsにjoint_valuesを渡す際はdegreeで代入する必要があります。
そのため、シミュレーションと実機で引数の渡し方が違い、少し不便に感じます。
可能であれば、どちらかに統一していただけると嬉しいです。

**Comment by wanweiwei07** [comment]
修正しました．
