### ISSUE TITLE
self collided bug

### ISSUE THREAD

**Issue by chenhaox** [wanweiwei07/wrs#20]
I found a case that the yumi robot collided with itself but `is_collided` function reports `false`. The photo shows the situation.
![image](https://user-images.githubusercontent.com/3233768/121503751-5215fd80-ca1c-11eb-934c-4669ce731629.png)
I thought something wrong happening to self collision detection.

The code is following:
```Python
base = wd.World(cam_pos=[2, 0, 1.5], lookat_pos=[0, 0, .2])
robot_s = ym.Yumi()                                                          # simulation robot 
jnts= np.array([-1.95503661, - 1.50237315,  1.15998945,  1.02486284 , 3.42901897,- 0.30705591,
            1.83156597])  
robot_s.fk("rgt_arm",jnts)
robot_s.gen_meshmodel().attach_to(base)
robot_s.show_cdprimit()
print(robot_s.is_collided())
base.run()
```

**Comment by wanweiwei07** [comment]
Thanks! The bug is corrected.
