### ISSUE TITLE
Add "namespace" to `.proto` file of grpc server

### ISSUE THREAD

**Issue by chenhaox** [wanweiwei07/wrs#21]
When using multiple clients, the grpc client without a "namespace" will result a name conflict problems. For example, message 
 "Empty" is defined in both `A.proto` and `B.proto`. If I use two clients using the `A.proto` and `B.proto` respectively. The name conflict error will occur since the message "Empty" is defined in both `A.proto` and `B.proto`. 

I thought adding a "namespace" can solve the problem.
Here is a link. It may helpful.
https://developers.google.com/protocol-buffers/docs/proto3#packages

**Comment by wanweiwei07** [comment]
Let me check this problem when I drop by next time.
