### ISSUE TITLE
Nextage control issue

### ISSUE THREAD

**Issue by xinyizzzhang** [wanweiwei07/wrs#25]
In robot_con/nxt/nxtrobot_server.py, function `closeHandToolRgt` line 121, 

```
self._robot.gripper_r_close()
```

should be 

```
self._robot._hands.gripper_r_close()
```
Same problem in function `closeHandToolLft` line 129, `openHandToolRgt` line 137, `openHandToolLft` line 145

**Comment by wanweiwei07** [comment]
谢谢，好像是用法的问题。什么时候有空可以到办公室找我讨论一下。
