### ISSUE TITLE
".set_rotmat"  in  geometricmodel.py

### ISSUE THREAD

**Issue by KentoNakatsuru** [wanweiwei07/wrs#3]
geometricmodel.pyの中にある.set_rotmatが反映されないです．

**Comment by wanweiwei07** [comment]
私の方は問題なさそうですが、、例えば、geometricmodel.pyファイルを直接実行すると、回転されたウサギが出ますよね．

**Comment by KentoNakatsuru** [comment]
解決しました！ありがとうございます！
