### ISSUE TITLE
robot_mathのrotmat_from_eulerについて

### ISSUE THREAD

**Issue by hrhryusuke** [wanweiwei07/wrs#38]
robot_math中の関数rotmat_from_eulerの引数についてです．
角度の単位を度（degree）と表記されていますが，この関数の元となる_euler_matrixの処理でmath.sin()などに渡すことを考えると角度の単位はラジアン（radian）が正しいのではないかと思います．

ご確認よろしくお願い致します．

**Comment by wanweiwei07** [comment]
どうもありがとうございます．これはラジアンのはずです．コードを更新しました．
