### ISSUE TITLE
Incorrect data type check for  `data_adaptor.pandageom_from_points` 

### ISSUE THREAD

**Issue by chenhaox** [wanweiwei07/wrs#48]
The parameter `rgba_list` for function `data_adaptor.pandageom_from_points`  (https://github.com/wanweiwei07/wrs/blob/8c91537c17a23842d0acfbf44f1b6b03a9614e3f/basis/data_adapter.py#L319-L320)  can be `NumPy array`. Otherwise, it takes time to adapt a NumPy array to a list. In addition, `rgba_list` is finally converted to a NumPy array (https://github.com/wanweiwei07/wrs/blob/8c91537c17a23842d0acfbf44f1b6b03a9614e3f/basis/data_adapter.py#L322-L324). The data type check here seems to be improper.

**Comment by wanweiwei07** [comment]
I have updated this code. Could you examine if it works? Both 3-column and 4-column color should work now.
