### ISSUE TITLE
collisonchecker.pyの中のis_collided

### ISSUE THREAD

**Issue by KentoNakatsuru** [wanweiwei07/wrs#5]
File "/home/kento/PycharmProjects/wrs/robotsim/_kinematics/collisionchecker.py", line 156, in is_collided
    obstacle.objpdnp.reparentTo(base.render)
NameError: name 'base' is not defined
上記のようなエラーが出ます．

**Comment by wanweiwei07** [comment]
なるほど、恐らくリモート表示を使っていますので、ローカルなベースはないですね．修正しました．最後ベースに付けなく、もともとの親（ベースでも可能、リモートの場合何もない）に付けました．

**Comment by KentoNakatsuru** [comment]
ありがとうございます
