### ISSUE TITLE
`manipulator_interface`の`get_jnt_ranges`

### ISSUE THREAD

**Issue by tkmrym** [wanweiwei07/wrs#52]
ロボットの関節可動範囲を取得しようとrobot_sの`get_jnt_ranges(component_name)`を呼び出したところエラーが出ました．

確認したところ，`manipulator_interface.py`の`get_jnt_ranges(self)`で`self.jlc.get_jnt_ranges()`がリターンされていたのですが，JLChainにそのようなメソッドは存在せず，代わりに`jnt_ranges`というプロパティがありました．

そのため，`self.jlc.get_jnt_ranges()`ではなく`self.jlc.jnt_ranges`をリターンすべきかと思います．

**Comment by wanweiwei07** [comment]
manipulator_interface.pyファイルの81行ですね？すでに修正したそうです．もし問題が続きであれば、新たなISSUEを作成ください．
