### ISSUE TITLE
Bug in Robotiq140

### ISSUE THREAD

**Issue by chenhaox** [wanweiwei07/wrs#67]
https://github.com/wanweiwei07/wrs/blob/4b676d47c0b9b783b38cf3902f888d28eaba8761/robot_sim/end_effectors/gripper/robotiq140/robotiq140.py#L136

When calculating the `jaw_center_pos_rel`, it uses the global coordinate of the `lft_outer`. It should use the local coordinate. Otherwise, when the `lft_outer` changes, the following code is incorrect.

https://github.com/wanweiwei07/wrs/blob/4b676d47c0b9b783b38cf3902f888d28eaba8761/robot_sim/end_effectors/gripper/robotiq140/robotiq140.py#L222

**Comment by wanweiwei07** [comment]
Thx! Corrected.
