### ISSUE TITLE
Issues in the new JLChain

### ISSUE THREAD

**Issue by chenhaox** [wanweiwei07/wrs#77]
1. Return value error of forward Kinematics

   https://github.com/wanweiwei07/wrs/blob/2848f951c0c8a0442be6dde638fd0f15adbe7b0e/robot_sim/kinematics/jlchain.py#L156-L160

   `tcp_gl_rotmat, tcp_gl_rotmat, j_mat` and `tcp_gl_rotmat, tcp_gl_rotmat` should be `tcp_gl_pos, tcp_gl_rotmat, j_mat` and `tcp_gl_pos, tcp_gl_rotmat`

**Comment by wanweiwei07** [comment]
corrected. Thanks!
