### ISSUE TITLE
Color setting conflict in gm.gen_pointcloud

### ISSUE THREAD

**Issue by chenhaox** [wanweiwei07/wrs#79]
When generating the point cloud, the `pcd_pdndp` data will first be transferred to the `StaticGeometricModel`, as the following line.

https://github.com/wanweiwei07/wrs/blob/6895529ee09d0ceef8052991803a24386fb51ce8/modeling/geometric_model.py#L1125

However, the `StaticGeometricModel` will set the model as a predefined color by default, as the following line:

https://github.com/wanweiwei07/wrs/blob/6895529ee09d0ceef8052991803a24386fb51ce8/modeling/geometric_model.py#L116

This raises the color setting conflict (I guess this conflict also exists in other `gen_xxx` functions).

**Comment by wanweiwei07** [comment]
True. Corrected.
